# Docs - https://alacritty.org/config-alacritty.html
# Themes - https://github.com/alacritty/alacritty-theme

# setup wsl on alacritty
[terminal]
shell = { program = "wsl", args = ["--cd ~"] }

[general]
live_config_reload = true
import = ["C:\\Users\\felipe\\AppData\\Roaming\\alacritty\\themes\\material-darker-high-contrast.toml"]

[env]
TERM = "xterm-256color"
LC_CTYPE = "en_US.UTF-8"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.98
dimensions = {columns = 80, lines = 20}
padding = {x = 10, y = 10}

[font]
size = 15
normal = {family = "JetBrains Mono", style = "Regular"}

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Beam", blinking = "Off" }
unfocused_hollow = true

# ctrl + right click to paste
[mouse]
bindings = [
  { mouse = "Right", mods = "Control", action = "Paste" },
]

[keyboard]
bindings = [
{key = "f", mods = "Alt|Shift", action = "ToggleFullscreen"},
{key = "q", mods="Control", action = "Quit"}
]
