[colors.primary]
background = "#212121" # Editor background
foreground = "#EEFFFF" # Editor foreground
dim_foreground = "#848484" # Baseado em tab.inactiveForeground
bright_foreground = "#FFFFFF" # Baseado em tab.activeForeground

[colors.cursor]
text = "#212121" # Mesmo que o background principal
cursor = "#FFCC00" # editorCursor.foreground

[colors.vi_mode_cursor]
text = "#212121" # Mesmo que o background principal
cursor = "#C792EA" # Cor usada para keywords/storage, bom para destaque

[colors.search.matches]
foreground = "#EEFFFF" # Foreground principal
background = "#80CBC4" # **Removido o alpha (era #80CBC440)**

[colors.search.focused_match]
foreground = "#212121" # Background principal para contraste
background = "#80CBC4" # selection.background

[colors.footer_bar]
foreground = "#EEFFFF" # Foreground principal
background = "#1a1a1a" # statusBar.background

[colors.hints.start]
foreground = "#212121" # Background principal para contraste
background = "#FFCB6B" # Amarelo do tema

[colors.hints.end]
foreground = "#EEFFFF" # Foreground principal
background = "#4A4A4A" # terminal.ansiBrightBlack

[colors.selection]
text = "#EEFFFF" # Foreground principal
background = "#616161" # **Removido o alpha (era #61616150)**

[colors.normal]
black = "#000000" # terminal.ansiBlack
red = "#FF5370" # terminal.ansiRed
green = "#C3E88D" # terminal.ansiGreen
yellow = "#FFCB6B" # terminal.ansiYellow
blue = "#82AAFF" # terminal.ansiBlue
magenta = "#C792EA" # terminal.ansiMagenta
cyan = "#89DDFF" # terminal.ansiCyan
white = "#ffffff" # terminal.ansiWhite

[colors.bright]
black = "#4A4A4A" # terminal.ansiBrightBlack
red = "#FF5370" # terminal.ansiBrightRed
green = "#C3E88D" # terminal.ansiBrightGreen
yellow = "#FFCB6B" # terminal.ansiBrightYellow
blue = "#82AAFF" # terminal.ansiBrightBlue
magenta = "#C792EA" # terminal.ansiBrightMagenta
cyan = "#89DDFF" # terminal.ansiBrightCyan
white = "#ffffff" # terminal.ansiBrightWhite